{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source \"/Users/giacomoibba/Desktop/mainnet/00/OCSafeMath.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/00/00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7_Punisher.sol:24:1:\n   |\n24 | import \"./OCSafeMath.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/00/Permissions.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/00/00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7_Punisher.sol:26:1:\n   |\n26 | import \"./Permissions.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/00/ILocker.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/00/00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7_Punisher.sol:27:1:\n   |\n27 | import \"./ILocker.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/00/ValidatorService.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/00/00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7_Punisher.sol:29:1:\n   |\n29 | import \"./ValidatorService.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/00/DelegationController.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/00/00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7_Punisher.sol:30:1:\n   |\n30 | import \"./DelegationController.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
